### ISSUE TITLE
建议添加色谱的解释

### ISSUE THREAD

**Issue by YangKian** [zerosoul/chinese-colors#1]
非常棒的项目！偶然看到了作者在http://blog.sina.com.cn/s/blog_5c3b139d0101deia.html 中提供的补充，请问是否可以考虑将完美色谱栏后面针对每个颜色的注释也添加到项目里呢？期待项目越做越好！

**Comment by zerosoul** [comment]
> 非常棒的项目！偶然看到了作者在http://blog.sina.com.cn/s/blog_5c3b139d0101deia.html 中提供的补充，请问是否可以考虑将完美色谱栏后面针对每个颜色的注释也添加到项目里呢？期待项目越做越好！

感谢反馈，注释其实已经有，只不过放在了元素的title上了，在PC上浏览，鼠标放到对应的颜色，会出来注释。这样做的原因是尽量保持界面的简介，不得不牺牲下元素个数，尤其移动端，元素过度，显得杂乱。

**Comment by YangKian** [comment]
@zerosoul 找到了，感谢解惑！
