### ISSUE TITLE
iOS  PWA  问题

### ISSUE THREAD

**Issue by w316525096** [zerosoul/chinese-colors#10]
iOS 12.4.2
PWA书签
点开之后显示空白.

前几个星期保存成PWA,点开正常显示.
不确定是不是更新12.4.2后的问题.
删除PWA书签,重新加入,还是空白.

![IMG_0602](https://user-images.githubusercontent.com/25398881/66114573-ad65da80-e601-11e9-83db-7481cab88ba9.PNG)

**Comment by zerosoul** [comment]
> iOS 12.4.2
> PWA书签
> 点开之后显示空白.
> 
> 前几个星期保存成PWA,点开正常显示.
> 不确定是不是更新12.4.2后的问题.
> 删除PWA书签,重新加入,还是空白.
> 
> ![IMG_0602](https://user-images.githubusercontent.com/25398881/66114573-ad65da80-e601-11e9-83db-7481cab88ba9.PNG)

确实是个问题，前些天，换域名导致的。具体和service worker有关，暂时没找到好的解决问题，请直接访问：https://colors.ichuantong.cn/    

原来的网址已废弃，做了301跳转，还不行的话，清理下浏览器缓存...
