### ISSUE TITLE
手机端内容太空旷

### ISSUE THREAD

**Issue by gooolan** [zerosoul/chinese-colors#2]
- 手机端生成的壁纸太过空旷，希望能将画加进去
- 手机和PC都将诗句加进去就更好了

**Comment by zerosoul** [comment]
> * 手机端生成的壁纸太过空旷，希望能将画加进去

应该是大部分颜色都没有配图（配图不好找😂，有合适的配图可以发给我），不过没有配图的会默认配一个 国色 两个字的图。
诗句加到壁纸中这个可以有，感谢反馈。

**Comment by zerosoul** [comment]
> * 手机端生成的壁纸太过空旷，希望能将画加进去
> * 手机和PC都将诗句加进去就更好了

诗句已加入壁纸中
