### ISSUE TITLE
能提供诗词复制功能吗

### ISSUE THREAD

**Issue by einnse** [zerosoul/chinese-colors#4]
网站加上诗词复制功能应该更好。copy-to-clipboard自己试着写没生效，求助。

**Comment by zerosoul** [comment]
> 网站加上诗词复制功能应该更好。copy-to-clipboard自己试着写没生效，求助。

做这个功能没问题，很简单，但是没必要。

后面会考虑加上诗词释义和对应的搜索引擎链接。
