### ISSUE TITLE
页面中黄色值看不大清楚

### ISSUE THREAD

**Issue by 15067832187** [zerosoul/chinese-colors#6]
有好多颜色里面的黄色色值，可能是由于外面颜色影响还是我本身眼神不好，感觉看起来不是很明显，有些晃眼。如果可以的话希望作者能稍稍修改下，谢谢。顺带一提，这个做的真的很棒，点个赞！！

**Comment by 15067832187** [comment]
还有白色的页面，有几个白色里面的颜色整个页面的文字都看不清楚；

**Comment by zerosoul** [comment]
> 有好多颜色里面的黄色色值，可能是由于外面颜色影响还是我本身眼神不好，感觉看起来不是很明显，有些晃眼。如果可以的话希望作者能稍稍修改下，谢谢。顺带一提，这个做的真的很棒，点个赞！！

谢谢，这个问题我也注意到了，正在想办法优化下。

**Comment by 15067832187** [comment]
对了颜色旁边的诗词，如果配上的是形容这个颜色，或者描写这个颜色的会更棒感觉。

**Comment by zerosoul** [comment]
> 对了颜色旁边的诗词，如果配上的是形容这个颜色，或者描写这个颜色的会更棒感觉。

对，这个目前还没找到合适的改进方式，如果每个颜色找一个写死，工作量有点大，而且对文化水平要求也有点高，有中文专业的同学或者古诗词爱好者帮助一下，就太好了。😀

**Comment by zerosoul** [comment]
> 还有白色的页面，有几个白色里面的颜色整个页面的文字都看不清楚；

反馈的问题，已优化。
