### ISSUE TITLE
切换颜色时,那些诗句会排版乱掉

### ISSUE THREAD

**Issue by caizhichao** [zerosoul/chinese-colors#9]

**Comment by zerosoul** [comment]
用的什么设备，什么浏览器访问的。最好有个截图。

**Comment by caizhichao** [comment]
> 用的什么设备，什么浏览器访问的。最好有个截图。

![Screenshot_2019-09-29-18-45-46-599_com quark brow](https://user-images.githubusercontent.com/25865457/65843693-960ac100-e365-11e9-83e3-270d6cd4f156.png)
![Screenshot_2019-09-29-18-47-44-611_com tencent an](https://user-images.githubusercontent.com/25865457/65843694-96a35780-e365-11e9-881b-a38368c0a369.png)
![Screenshot_2019-09-29-18-47-49-454_com tencent an](https://user-images.githubusercontent.com/25865457/65843696-96a35780-e365-11e9-93cb-67591761f393.png)
![H%1%7($%@30 9RF4PQ`U~R8](https://user-images.githubusercontent.com/25865457/65843773-0e718200-e366-11e9-9f12-5e6f496ad539.png)

第一张是 夸克浏览器,右下角颜色出不来
第二三张是安卓版qq邮箱内的链接打开的
第四张是win10  google浏览器 版本 72.0.3626.121（正式版本） （32 位）,点击左侧按钮切换颜色时

**Comment by magicdict** [comment]
CSS地狱，兼容性可能有问题

**Comment by zerosoul** [comment]
> > 用的什么设备，什么浏览器访问的。最好有个截图。
> 
> ![Screenshot_2019-09-29-18-45-46-599_com quark brow](https://user-images.githubusercontent.com/25865457/65843693-960ac100-e365-11e9-83e3-270d6cd4f156.png)
> ![Screenshot_2019-09-29-18-47-44-611_com tencent an](https://user-images.githubusercontent.com/25865457/65843694-96a35780-e365-11e9-881b-a38368c0a369.png)
> ![Screenshot_2019-09-29-18-47-49-454_com tencent an](https://user-images.githubusercontent.com/25865457/65843696-96a35780-e365-11e9-93cb-67591761f393.png)
> ![H%1%7($%@30 9RF4PQ`U~R8](https://user-images.githubusercontent.com/25865457/65843773-0e718200-e366-11e9-9f12-5e6f496ad539.png)
> 
> 第一张是 夸克浏览器,右下角颜色出不来
> 第二三张是安卓版qq邮箱内的链接打开的
> 第四张是win10 google浏览器 版本 72.0.3626.121（正式版本） （32 位）,点击左侧按钮切换颜色时

感谢反馈，我重构了下这块的样式，现在应该好了。
